import "./globals.css";
import type { Metadata } from "next";
import UserContextProvider from "@/app/_context/user-context";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-[100%]">
      <body
        suppressHydrationWarning
        className="h-[100%] bg-pastel-lightGreen p-6 sm:p-10 max-w-[1200px] m-auto"
      >
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
